name: 'Get Versions'
description: 'Get Versions'

inputs:
  os:
    description: “The os name”
    required: false

outputs:
  versions:
    description: "get version matrix"
    value: ${{steps.get-versions.outputs.versions}}

runs:
  using: "composite"
  steps:
    - name: Get versions from directory structure
      id: get-versions
      run: |
        if [ -n ${{ inputs.os }} ]; then
            test_path="Dockerfiles/${{ inputs.os }}"
            dir_path="Dockerfiles/${{ inputs.os }}/*/"
            field=3
        else
            test_path="Dockerfiles"
            dir_path="Dockerfiles/*/"
            field=2
        fi
        if [ -d "${test_path}" ]; then
            echo "::set-output name=versions::$(ls -d ${dir_path} | cut -f${field} -d'/' | sort -n | jq -cnR '[inputs | select(length>0)]')"
        else
            echo "::set-output name=versions::[]"
        fi

      shell: bash
