name: 'Get versions wrapper'
description: 'Get versions wrapper'

outputs:
  almalinux-versions:
    description: "Alma Linux Versions"
    value: ${{steps.almalinux.outputs.versions}}
  alpine-versions:
    description: "Alpine Versions"
    value: ${{steps.alpine.outputs.versions}}
  amazonlinux-versions:
    description: "Amazon Linux Versions"
    value: ${{steps.amazonlinux.outputs.versions}}
  archlinux-versions:
    description: "Arch Linux Versions"
    value: ${{steps.archlinux.outputs.versions}}
  centos-versions:
    description: "Centos Versions"
    value: ${{steps.centos.outputs.versions}}
  debian-versions:
    description: "Debian Versions"
    value: ${{steps.debian.outputs.versions}}
  oraclelinux-versions:
    description: "Oracle Linux Versions"
    value: ${{steps.oraclelinux.outputs.versions}}
  photon-versions:
    description: "Photon Versions"
    value: ${{steps.photon.outputs.versions}}
  rockylinux-versions:
    description: "Rocky Linux Versions"
    value: ${{steps.rockylinux.outputs.versions}}
  scientificlinux-versions:
    description: "Scientific Linux Versions"
    value: ${{steps.scientificlinux.outputs.versions}}
  ubuntu-versions:
    description: "Ubuntu Versions"
    value: ${{steps.ubuntu.outputs.versions}}

runs:
  using: "composite"
  steps:
    - name: Get alma linux versions
      id: almalinux
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'almalinux'
    - name: Get alpine versions
      id: alpine
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'alpine'
    - name: Get amazon linux versions
      id: amazonlinux
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'amazonlinux'
    - name: Get centos versions
      id: centos
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'centos'
    - name: Get debian versions
      id: debian
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'debian'
    - name: Get oracle linux versions
      id: oraclelinux
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'oraclelinux'
    - name: Get photon versions
      id: photon
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'photon'
    - name: Get rocky linux versions
      id: rockylinux
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'rockylinux'
    - name: Get scientific linux versions
      id: scientificlinux
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'sl'
    - name: Get ubuntu versions
      id: ubuntu
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'ubuntu'
