name: 'Get versions wrapper'
description: 'Get versions wrapper'

outputs:
  alpine-versions:
    description: "Alpine Versions"
    value: ${{steps.alpine.outputs.versions}}
  centos-versions:
    description: "Centos Versions"
    value: ${{steps.centos.outputs.versions}}
  debian-versions:
    description: "Debian Versions"
    value: ${{steps.debian.outputs.versions}}
  photon-versions:
    description: "Photon Linux Versions"
    value: ${{steps.photon.outputs.versions}}

runs:
  using: "composite"
  steps:
    - name: Get alpine versions
      id: alpine
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'alpine'
    - name: Get centos versions
      id: centos
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'centos'
    - name: Get debian versions
      id: debian
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'debian'
    - name: Get photon linux versions
      id: photon
      uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
      with:
        os: 'photon'
