name: 'Get Versions'
description: 'Get Versions'

inputs:
  os:
    description: “The os name”
    required: false

outputs:
  versions:
    description: "get version matrix"
    value: ${{steps.get-versions.outputs.versions}}

runs:
  using: "composite"
  steps:
    - name: Get ${{ inputs.os }} versions
      id: get-versions
      run: |
        if [ -z "${{ inputs.os }}" ]; then
          echo "::set-output name=versions::$(ls -d Dockerfiles/${{ inputs.os }}/*/ | cut -f3 -d'/' | sort -n | jq -cnR '[inputs | select(length>0)]'))"
        else
          echo "::set-output name=versions::$(ls -d Dockerfiles/*/ | cut -f3 -d'/' | sort -n | jq -cnR '[inputs | select(length>0)]'))"
        fi
      shell: bash
