name: Multiple OS Workflow

on:
  workflow_call:
    inputs:
      runs-on:
        description: Platform to execute on
        type: string
        default: ubuntu-latest
        required: false
      directory:
        required: true
        type: string
      lint:
        required: false
        type: boolean
        default: true
      publish_all:
        required: false
        type: boolean
        default: false
      publish_dh:
        required: false
        type: boolean
        default: false
      publish_gh:
        required: false
        type: boolean
        default: false
      ref:
        required: true
        type: string
      scan:
        required: false
        type: boolean
        default: false
      fail-fast:
        required: false
        type: boolean
        default: false
      max-parallel:
        required: false
        type: string
        default: 1

jobs:
  get-versions:
    name: Get versions
    runs-on: ${{ inputs.runs-on }}
    outputs:
      versions: ${{steps.get-versions.outputs.versions}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - name: Get version matrix
        id: get-versions
        uses: actionstoolbox/container-framework-actions/actions/get-versions-single@master
        with:
          os: ${{ inputs.directory }}
  build:
    runs-on: ${{ inputs.runs-on }}
    needs: get-versions
    if: ${{ needs.get-versions.outputs.versions != '[]' && needs.get-versions.outputs.versions != '' }}
    strategy:
      max-parallel: ${{ inputs.max-parallel }}
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        version: ${{ fromJson(needs.get-versions.outputs.versions) }}
    name: ${{ matrix.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.ref }}
      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Generate Dockerfile
        run: Dockerfiles/${{ inputs.directory }}/${{ matrix.version }}/manage.sh --generate
      - name: Run Hadolint
        if: ${{ inputs.lint }}
        run: bash <(curl -s https://raw.githubusercontent.com/CICDToolbox/hadolint/master/pipeline.sh)
      - name: Build Docker Container
        run: Dockerfiles/${{ inputs.directory }}/${{ matrix.version }}/manage.sh --build --clean
      - name: Run Docker Scan
        if: ${{ inputs.scan }}
        run: Dockerfiles/${{ inputs.directory }}/${{ matrix.version }}/manage.sh --scan
      - name: Publish Containers to Docker Hub
        if: ${{ inputs.publish_all || inputs.publish_dh }}
        run: echo "Publish Docker Hub"
      - name: Publish Containers to GitHub
        if: ${{ inputs.publish_all || inputs.publish_gh }}
        run: echo "Publish Github"
